### ISSUE TITLE
Update to Polymer 2

### ISSUE THREAD

**Issue by lastmjs** [oscarmcm/profile-vcard#1]
This thing looks awesome! Any chance it could get updated to Polymer 2?

**Comment by oscarmcm** [comment]
@lastmjs Thanks, I'll update this as soon as possible 👍

**Comment by mmilutinovic013** [comment]
I just coded up a solution to transfer this to Polymer 2.0. I can throw up a PR if you'd like to add this in or put it in a separate branch! #2

**Comment by oscarmcm** [comment]
Created a new release tag for it [V3.0.0](https://github.com/oscarmcm/profile-vcard/releases/tag/v3.0.0)
Big kudos to @mmilutinovic1313 for the help 👏
